#!/usr/bin/env node
// AI Firewall VPN — WireGuard key + config generator
// Generates real Curve25519 (X25519) keypairs and wg-quick configs
// for a server and N clients. Output goes to ./vpn-out/
import { generateKeyPairSync, randomBytes } from 'crypto';
import { mkdirSync, writeFileSync, existsSync, readFileSync } from 'fs';
import { join } from 'path';

const VERSION = '1.0.0';
const OUT_DIR = new URL('../vpn-out/', import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1');

const HELP = `
AI Firewall VPN — WireGuard config generator v${VERSION}

Generates a WireGuard server config plus one .conf per client (phones,
laptops, desktops). WireGuard is the audited, kernel-native VPN protocol
used by Mullvad, Proton, and most commercial VPNs.

Usage:
  node vpn/generate.mjs --endpoint vpn.example.com --port 51820 --clients 3

Options:
  --endpoint <host>    Public IP or hostname of your VPN server (required)
  --port <n>           UDP listen port, default 51820
  --clients <n>        Number of client configs to generate, default 3
  --subnet <cidr>      VPN subnet, default 10.77.0.0/24
  --out <dir>          Output directory, default ./vpn-out
  --no-preshared       Skip pre-shared keys (not recommended)
  --bundle-server      Also write a self-contained server-deploy.sh (no repo needed on VPS)
  --help               Show this help

Then:
  1. Copy vpn-out/server.conf to your VPS:  sudo wg-quick up /path/server.conf
  2. Import each client .conf into the official WireGuard app / our client installer.

Security notes:
  - Keys are generated locally with Node's native X25519 (Curve25519).
  - Use --no-preshared only for testing. Pre-shared keys add post-quantum
    resistance against stored-ciphertext decryption.
  - Treat vpn-out/ like secrets: never commit it.
`;

function x25519Keypair() {
  const { publicKey, privateKey } = generateKeyPairSync('x25519');
  const spki = publicKey.export({ format: 'der', type: 'spki' });
  const pub = spki.subarray(spki.length - 32).toString('base64');
  const priv = privateKey.export({ format: 'der', type: 'pkcs8' });
  const rawPriv = priv.subarray(priv.length - 32).toString('base64');
  return { pub, priv: rawPriv };
}

function parseArgs(argv) {
  const opts = {
    endpoint: null, port: 51820, clients: 3, subnet: '10.77.0.0/24', out: OUT_DIR, preshared: true, bundleServer: false
  };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--help') { console.log(HELP); process.exit(0); }
    if (a === '--endpoint') opts.endpoint = argv[++i];
    if (a === '--port') opts.port = parseInt(argv[++i], 10);
    if (a === '--clients') opts.clients = parseInt(argv[++i], 10);
    if (a === '--subnet') opts.subnet = argv[++i];
    if (a === '--out') opts.out = argv[++i];
    if (a === '--no-preshared') opts.preshared = false;
    if (a === '--bundle-server') opts.bundleServer = true;
  }
  return opts;
}

function ipFromSubnet(subnet, n) {
  const [base, mask] = subnet.split('/');
  const octets = base.split('.').map(Number);
  octets[3] = n + 1;
  return octets.join('.') + '/' + mask;
}

function ipPlain(subnet, n) {
  return ipFromSubnet(subnet, n).split('/')[0];
}

function main() {
  const opts = parseArgs(process.argv.slice(2));
  if (!opts.endpoint) {
    console.error('ERROR: --endpoint is required (public IP or hostname of your VPN server).');
    console.error(HELP);
    process.exit(1);
  }

  mkdirSync(opts.out, { recursive: true });

  const server = x25519Keypair();
  const [base, maskBits] = opts.subnet.split('/');
  const serverIp = base.split('.')[0] + '.' + base.split('.')[1] + '.' + base.split('.')[2] + '.1/' + maskBits;
  const serverIpPlain = serverIp.split('/')[0];

  const summary = [];
  const clients = [];

  for (let i = 1; i <= opts.clients; i++) {
    const client = x25519Keypair();
    const psk = opts.preshared ? randomBytes(32).toString('base64') : null;
    const clientIp = ipPlain(opts.subnet, i);
    clients.push({ ...client, psk, clientIp, index: i });
  }

  // ── server.conf ──
  let serverConf = `[Interface]
Address = ${serverIp}
ListenPort = ${opts.port}
PrivateKey = ${server.priv}
# To route ALL traffic through the VPN, add:
# PostUp = iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE; sysctl -w net.ipv4.ip_forward=1
# PostDown = iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
# (see vpn/server/setup.sh which configures this automatically)

`;
  for (const c of clients) {
    serverConf += `[Peer]
# Client ${c.index}
PublicKey = ${c.pub}
${c.psk ? 'PresharedKey = ' + c.psk + '\n' : ''}AllowedIPs = ${c.clientIp}/32

`;
    summary.push(`Client ${c.index}: ${c.clientIp}`);
  }
  writeFileSync(join(opts.out, 'server.conf'), serverConf);

  // ── client confs ──
  for (const c of clients) {
    const conf = `[Interface]
# Generated by AI Firewall VPN (client ${c.index})
Address = ${c.clientIp}/32
PrivateKey = ${c.priv}
# Optional DNS: uncomment to force DNS through the tunnel
# DNS = 1.1.1.1, 1.0.0.1

[Peer]
# Server
PublicKey = ${server.pub}
${c.psk ? 'PresharedKey = ' + c.psk + '\n' : ''}Endpoint = ${opts.endpoint}:${opts.port}
AllowedIPs = 0.0.0.0/0, ::/0
PersistentKeepalive = 25
`;
    writeFileSync(join(opts.out, `client${c.index}.conf`), conf);
  }

  // ── summary ──
  const meta = `# AI Firewall VPN — generated ${new Date().toISOString()}
# Endpoint: ${opts.endpoint}:${opts.port}
# Subnet: ${opts.subnet}
# Server public key: ${server.pub}
# Server IP (internal): ${serverIpPlain}
#
${summary.join('\n')}
#
# SECURITY: keep this directory private. Client .conf files contain your
# private keys and full-tunnel (0.0.0.0/0) routes.
`;
  writeFileSync(join(opts.out, 'README.txt'), meta);

  // ── optional self-contained server deploy script (no repo needed on VPS) ──
  if (opts.bundleServer) {
    const defaultIf = '$(ip route show default | awk \'{print $5}\' | head -n1)';
    const deploy = `#!/usr/bin/env bash
# AI Firewall VPN — self-contained server deploy (copied here via --bundle-server)
# Run on your Ubuntu/Debian VPS:
#   sudo bash /tmp/server-deploy.sh
# Internet-facing wireguard config is embedded below by vpn/generate.mjs.
set -euo pipefail
export DEBIAN_FRONTEND=noninteractive

echo "==> Installing WireGuard + tools"
apt-get update -y
apt-get install -y wireguard wireguard-tools iptables

echo "==> Enabling IPv4 forwarding"
{ grep -q net.ipv4.ip_forward /etc/sysctl.conf && sed -i 's/^#*net.ipv4.ip_forward.*/net.ipv4.ip_forward=1/' /etc/sysctl.conf; } || echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
sysctl -w net.ipv4.ip_forward=1

echo "==> Installing server config"
cat > /etc/wireguard/wg0.conf <<'WGCONF'
${serverConf.trim()}
WGCONF
chmod 600 /etc/wireguard/wg0.conf

echo "==> Adding NAT masquerade on default interface"
DEFAULT_IF=\$(ip route show default | awk '{print \$5}' | head -n1)
DEFAULT_IF="\${DEFAULT_IF:-eth0}"
sed -i "/^\[Interface\]/a \\
PostUp = iptables -t nat -A POSTROUTING -o \${DEFAULT_IF} -j MASQUERADE; iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT \\
PostDown = iptables -t nat -D POSTROUTING -o \${DEFAULT_IF} -j MASQUERADE; iptables -D FORWARD -i wg0 -j ACCEPT; iptables -D FORWARD -o wg0 -j ACCEPT" /etc/wireguard/wg0.conf

echo "==> Starting WireGuard"
systemctl enable wg-quick@wg0 2>/dev/null || true
wg-quick down wg0 2>/dev/null || true
wg-quick up wg0

echo ""
echo "==> Status"
wg show
echo ""
echo "DONE. VPN server live. Open UDP ${opts.port} for clients:"
echo "  ufw allow ${opts.port}/udp"
`;
    const deployPath = join(opts.out, 'server-deploy.sh');
    writeFileSync(deployPath, deploy);
    console.log('  Bundled self-contained: ' + deployPath);
    console.log('  Copy-paste one-liner (from this machine, secrets never uploaded):');
    console.log('    scp "' + deployPath + '" root@' + opts.endpoint + ':/tmp/server-deploy.sh && ssh root@' + opts.endpoint + ' "sudo bash /tmp/server-deploy.sh"');
    console.log('');
  }

  console.log('');
  console.log('  AI Firewall VPN — configs written to: ' + opts.out);
  console.log('  ' + '─'.repeat(50));
  console.log('  Server: ' + opts.endpoint + ':' + opts.port + '  (UDP)');
  console.log('  Subnet: ' + opts.subnet + '  |  Server internal IP: ' + serverIpPlain);
  console.log('  Server public key: ' + server.pub);
  console.log('');
  console.log('  Clients:');
  summary.forEach((s) => console.log('    ' + s));
  console.log('');
  console.log('  Files: server.conf + client1.conf ... client' + opts.clients + '.conf');
  console.log('');
  console.log('  Next: run vpn/server/setup.sh on the VPS, then import a client.conf');
  console.log('        into the WireGuard app or vpn/client/install.ps1.');
  console.log('');
}

main();
