#!/usr/bin/env bash
# AI Firewall VPN — Ubuntu/Debian VPS server installer
# Installs WireGuard, enables IP forwarding + NAT, and loads a server config.
#
# Usage on your VPS (Ubuntu 20.04+/22.04/24.04, Debian 11/12):
#   sudo bash setup.sh /path/to/server.conf
#
# Requirements:
#   - A VPS with a public IP (any provider: DigitalOcean, Vultr, Hetzner, Linode...)
#   - server.conf generated by: node vpn/generate.mjs --endpoint <VPS_IP>
#
# IMPORTANT: this is the one external component that must be purchased/hosted.
# We don't operate servers — you run your own, and your clients connect to it.

set -euo pipefail

CONF="${1:-}"
if [[ -z "$CONF" || ! -f "$CONF" ]]; then
  echo "Usage: sudo bash $0 /path/to/server.conf"
  echo ""
  echo "Generate it first on your workstation:"
  echo "  node vpn/generate.mjs --endpoint YOUR_VPS_PUBLIC_IP --clients N"
  exit 1
fi

echo "==> Installing WireGuard + tools"
export DEBIAN_FRONTEND=noninteractive
apt-get update -y
apt-get install -y wireguard wireguard-tools iptables

echo "==> Enabling IPv4 forwarding"
if grep -q "net.ipv4.ip_forward" /etc/sysctl.conf 2>/dev/null; then
  sed -i 's/^#*net.ipv4.ip_forward.*/net.ipv4.ip_forward=1/' /etc/sysctl.conf
else
  echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
fi
sysctl -w net.ipv4.ip_forward=1

echo "==> Finding primary network interface"
DEFAULT_IF=$(ip route show default | awk '{print $5}' | head -n1)
DEFAULT_IF="${DEFAULT_IF:-eth0}"
echo "    Using interface: $DEFAULT_IF"

echo "==> Installing server config"
cp "$CONF" /etc/wireguard/wg0.conf
chmod 600 /etc/wireguard/wg0.conf

# Add NAT masquerade + restart rules to the [Interface] section if not present
if ! grep -q "MASQUERADE" /etc/wireguard/wg0.conf; then
  sed -i "/^\[Interface\]/a \\
PostUp = iptables -t nat -A POSTROUTING -o ${DEFAULT_IF} -j MASQUERADE; iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT \\
PostDown = iptables -t nat -D POSTROUTING -o ${DEFAULT_IF} -j MASQUERADE; iptables -D FORWARD -i wg0 -j ACCEPT; iptables -D FORWARD -o wg0 -j ACCEPT" /etc/wireguard/wg0.conf
fi

echo "==> Starting WireGuard"
systemctl enable wg-quick@wg0 2>/dev/null || true
wg-quick down wg0 2>/dev/null || true
wg-quick up wg0

echo ""
echo "==> Status"
wg show
echo ""
PUB=$(ip -4 addr show wg0 2>/dev/null | awk '/inet /{print $2}' | cut -d'/' -f1)
echo "VPN server internal IP: ${PUB:-10.77.0.1}"
echo ""
echo "DONE. Your VPN is live."
echo ""
echo "Next steps on the client:"
echo "  1. Copy a clientN.conf to your device"
echo "  2. Import it into the WireGuard app, or run:"
echo "       # Windows:  powershell -File vpn/client/install.ps1 -Config client1.conf"
echo "       # Linux:    sudo wg-quick up client1.conf"
echo ""
echo "Firewall tip: open UDP port 51820 (or your --port) for your clients."
echo "  ufw allow 51820/udp"
